version: '3.7'

services:
    laravel.test:
        build:
            context: docker
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-85}:80'
        volumes:
            - '.:/var/www/html'
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        networks:
            - appflame_task_network
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3506}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'appflame-mysql:/var/lib/mysql'
        networks:
            - appflame_task_network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6479}:6379'
        volumes:
            - 'appflame-redis:/data'
        networks:
            - appflame_task_network
        healthcheck:
            test:
                CMD
                redis-cli
                ping
            retries: 3
            timeout: 5s
networks:
    appflame_task_network:
        driver: bridge
volumes:
    appflame-mysql:
        driver: local
    appflame-redis:
        driver: local
